-- local files = 'git ls-files -c -o --exclude-standard'
--
-- local git_files = function(arg)
-- 	local res = vim.split(vim.trim(io.popen(files):read('*a')), '\n')
-- 	return arg and vim.tbl_filter(function(f)
-- 		return f:match(arg)
-- 	end, res) or {}
-- end
--
-- local command = function(opts)
-- 	for _, arg in ipairs(opts.fargs) do
-- 		vim.cmd.edit { args = { arg } }
-- 	end
-- end
--
-- vim.api.nvim_create_user_command('Files', command, {
-- 	complete = git_files,
-- 	nargs = '*',
-- })
